-- ============================================================
-- SSMSPL Ferry Boat Ticketing System
-- DDL Script – Complete Schema
-- Compatible with PostgreSQL 14+
-- ============================================================

-- Run this script against:
--   ssmspl_db_dev  (development)
--   ssmspl_db_test (testing)
--   ssmspl_db_prod (production)

-- ============================================================
-- EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- ENUMS
-- ============================================================
DO $$ BEGIN
    CREATE TYPE user_role_enum AS ENUM (
        'SUPER_ADMIN',
        'ADMIN',
        'MANAGER',
        'BILLING_OPERATOR',
        'TICKET_CHECKER'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- TABLES
-- ============================================================

-- Branches table (jetty/location management)
CREATE TABLE IF NOT EXISTS branches (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(15) NOT NULL UNIQUE,
    address             VARCHAR(255) NOT NULL,
    contact_nos         VARCHAR(255),
    latitude            NUMERIC(21,15),
    longitude           NUMERIC(21,15),
    sf_after            TIME WITH TIME ZONE,
    sf_before           TIME WITH TIME ZONE,
    last_ticket_no      BIGINT NOT NULL DEFAULT 0,
    last_booking_no     BIGINT NOT NULL DEFAULT 0,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Routes table (connects two branches)
CREATE TABLE IF NOT EXISTS routes (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id_one       INTEGER NOT NULL REFERENCES branches(id),
    branch_id_two       INTEGER NOT NULL REFERENCES branches(id),
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Users table (authentication + RBAC)
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) NOT NULL UNIQUE,
    username        VARCHAR(100) NOT NULL UNIQUE,
    full_name       VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    role            user_role_enum NOT NULL DEFAULT 'TICKET_CHECKER',
    route_id        INTEGER REFERENCES routes(id),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    last_login      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ
);

-- Boats table (ferry/vessel management)
CREATE TABLE IF NOT EXISTS boats (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(30) NOT NULL UNIQUE,
    no                  VARCHAR(18) NOT NULL UNIQUE,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT boat_name_length CHECK (length(name) >= 5 AND length(name) <= 30),
    CONSTRAINT boat_no_length   CHECK (length(no) >= 10 AND length(no) <= 30)
);

-- Items table (ticket item types)
CREATE TABLE IF NOT EXISTS items (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(60) NOT NULL UNIQUE,
    short_name          VARCHAR(30) NOT NULL UNIQUE,
    online_visiblity    BOOLEAN,
    is_vehicle          BOOLEAN DEFAULT FALSE,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Payment modes table
CREATE TABLE IF NOT EXISTS payment_modes (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description         VARCHAR NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Ferry schedules table (branch-wise departure times)
CREATE TABLE IF NOT EXISTS ferry_schedules (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           INTEGER NOT NULL REFERENCES branches(id),
    departure           TIME NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Item rates table (rate per item per route)
CREATE TABLE IF NOT EXISTS item_rates (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicable_from_date DATE,
    levy                NUMERIC(38,2),
    rate                NUMERIC(38,2),
    item_id             INTEGER REFERENCES items(id),
    route_id            INTEGER REFERENCES routes(id),
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT check_item_rate CHECK (rate > 1)
);

-- Portal users table (customer-facing authentication)
CREATE TABLE IF NOT EXISTS portal_users (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(60) NOT NULL,
    last_name           VARCHAR(60) NOT NULL,
    email               VARCHAR(90) NOT NULL,
    password            VARCHAR(60) NOT NULL,
    mobile              VARCHAR(60) NOT NULL,
    is_verified         BOOLEAN NOT NULL DEFAULT FALSE,
    remember_token      VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    profile_pic         BYTEA[],
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT portal_users_unique_email UNIQUE (email)
);

-- Email OTPs table (verification codes for registration and password reset)
CREATE TABLE IF NOT EXISTS email_otps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(90) NOT NULL,
    otp_hash    VARCHAR(255) NOT NULL,
    purpose     VARCHAR(20) NOT NULL,
    attempts    INTEGER NOT NULL DEFAULT 0,
    is_used     BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_email_otps_email_purpose ON email_otps(email, purpose);

-- Tickets table
CREATE TABLE IF NOT EXISTS tickets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           INTEGER NOT NULL REFERENCES branches(id),
    ticket_no           INTEGER NOT NULL,
    ticket_date         DATE NOT NULL,
    departure           TIME,
    amount              NUMERIC(9,2) NOT NULL,
    discount            NUMERIC(9,2),
    payment_mode_id     INTEGER NOT NULL,
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    net_amount          NUMERIC(9,2) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    checked_in_at       TIMESTAMPTZ,
    route_id            INTEGER NOT NULL REFERENCES routes(id),
    verification_code   UUID DEFAULT uuid_generate_v4(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT ticket_amount_check     CHECK (amount >= 1),
    CONSTRAINT ticket_net_amount_check CHECK (net_amount >= 1)
);

-- Ticket items table
CREATE TABLE IF NOT EXISTS ticket_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id           BIGINT NOT NULL REFERENCES tickets(id),
    item_id             INTEGER NOT NULL REFERENCES items(id),
    rate                NUMERIC(9,2) NOT NULL,
    levy                NUMERIC(9,2) NOT NULL,
    vehicle_no          VARCHAR(15),
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    quantity            INTEGER NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT check_item_quantity CHECK (quantity > 0)
);

-- Ticket payment table
CREATE TABLE IF NOT EXISTS ticket_payement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id           BIGINT NOT NULL,
    payment_mode_id     INTEGER NOT NULL REFERENCES payment_modes(id),
    amount              NUMERIC(9,2) NOT NULL,
    ref_no              VARCHAR(30),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT check_payement_amount CHECK (amount >= 1)
);

-- Refresh tokens (persistent refresh token store)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  UUID DEFAULT uuid_generate_v4(),
    updated_by  UUID DEFAULT uuid_generate_v4()
);

-- Company table (organization details)
CREATE TABLE IF NOT EXISTS company (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(120) NOT NULL,
    short_name          VARCHAR(60) NOT NULL,
    reg_address         VARCHAR(255) NOT NULL,
    gst_no              VARCHAR(60) NOT NULL,
    pan_no              VARCHAR(60) NOT NULL,
    tan_no              VARCHAR(60) NOT NULL,
    cin_no              VARCHAR(60) NOT NULL,
    contact             VARCHAR(255),
    email               VARCHAR(60) NOT NULL,
    sf_item_id          INTEGER,
    active_theme        VARCHAR(50) DEFAULT 'ocean',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Bookings table (online/portal bookings)
CREATE TABLE IF NOT EXISTS bookings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           INTEGER NOT NULL REFERENCES branches(id),
    booking_no          INTEGER NOT NULL,
    travel_date         DATE NOT NULL,
    departure           TIME,
    amount              NUMERIC(9,2) NOT NULL,
    discount            NUMERIC(9,2),
    payment_mode_id     INTEGER NOT NULL,
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    net_amount          NUMERIC(9,2) NOT NULL,
    route_id            INTEGER NOT NULL REFERENCES routes(id),
    portal_user_id      INTEGER NOT NULL REFERENCES portal_users(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT check_amount     CHECK (amount >= 1),
    CONSTRAINT check_net_amount CHECK (net_amount >= 1)
);

-- Booking items table
CREATE TABLE IF NOT EXISTS booking_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT NOT NULL REFERENCES bookings(id),
    item_id             INTEGER NOT NULL,
    rate                NUMERIC(9,2) NOT NULL,
    levy                NUMERIC(9,2) NOT NULL,
    vehicle_no          VARCHAR(15),
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    quantity            INTEGER NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT quantity_check CHECK (quantity > 0)
);

-- System update logs table (audit trail)
CREATE TABLE IF NOT EXISTS sys_update_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name         VARCHAR(30) NOT NULL,
    old_data            JSONB NOT NULL,
    new_data            JSONB NOT NULL,
    updated_by          UUID NOT NULL DEFAULT uuid_generate_v4(),
    updated_at          TIME WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Users
CREATE INDEX IF NOT EXISTS idx_users_email    ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role     ON users(role);

-- Refresh tokens
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id    ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);

-- ============================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_users_updated_at ON users;
CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- END OF DDL
-- ============================================================
