-- ============================================================
-- SSMSPL Ferry Boat Ticketing System
-- DDL Script – Complete Schema
-- Compatible with PostgreSQL 14+
-- Last updated: 2026-04-02
-- ============================================================

-- Run this script against:
--   ssmspl_db_dev  (development)
--   ssmspl_db_test (testing)
--   ssmspl_db_prod (production)
--
-- All CREATE TABLE statements reflect the current model state.
-- PATCH sections at the bottom handle migration of existing databases.

-- ============================================================
-- EXTENSIONS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- ENUMS
-- ============================================================
DO $$ BEGIN
    CREATE TYPE user_role_enum AS ENUM (
        'SUPER_ADMIN',
        'ADMIN',
        'MANAGER',
        'BILLING_OPERATOR',
        'TICKET_CHECKER'
    );
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================
-- TABLES
-- ============================================================

-- Branches table (jetty/location management)
CREATE TABLE IF NOT EXISTS branches (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(15) NOT NULL UNIQUE,
    address             VARCHAR(255) NOT NULL,
    contact_nos         VARCHAR(255),
    latitude            NUMERIC(21,15),
    longitude           NUMERIC(21,15),
    sf_after            TIME WITH TIME ZONE,
    sf_before           TIME WITH TIME ZONE,
    last_ticket_no      BIGINT NOT NULL DEFAULT 0,
    last_ticket_date    DATE,
    last_booking_no     BIGINT NOT NULL DEFAULT 0,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Routes table (connects two branches)
CREATE TABLE IF NOT EXISTS routes (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id_one       INTEGER NOT NULL REFERENCES branches(id),
    branch_id_two       INTEGER NOT NULL REFERENCES branches(id),
    is_active           BOOLEAN DEFAULT TRUE,
    multi_ticketing_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Users table (authentication + RBAC)
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) UNIQUE,
    username        VARCHAR(100) NOT NULL UNIQUE,
    full_name       VARCHAR(255) NOT NULL,
    mobile_number   VARCHAR(20),
    hashed_password VARCHAR(255) NOT NULL,
    role            user_role_enum NOT NULL DEFAULT 'TICKET_CHECKER',
    route_id        INTEGER REFERENCES routes(id),
    active_branch_id INTEGER REFERENCES branches(id),
    active_session_id VARCHAR(36),
    session_last_active TIMESTAMPTZ,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    last_login      TIMESTAMPTZ,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ
);

-- Boats table (ferry/vessel management)
CREATE TABLE IF NOT EXISTS boats (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(30) NOT NULL UNIQUE,
    no                  VARCHAR(18) NOT NULL UNIQUE,
    is_active           BOOLEAN DEFAULT TRUE,
    route_id            INTEGER REFERENCES routes(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT boat_name_length CHECK (length(name) >= 5 AND length(name) <= 30),
    CONSTRAINT boat_no_length   CHECK (length(no) >= 10 AND length(no) <= 30)
);
CREATE INDEX IF NOT EXISTS ix_boats_route_id ON boats(route_id);

-- Items table (ticket item types)
CREATE TABLE IF NOT EXISTS items (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(60) NOT NULL UNIQUE,
    short_name          VARCHAR(30) NOT NULL UNIQUE,
    online_visiblity    BOOLEAN,
    is_vehicle          BOOLEAN DEFAULT FALSE,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Payment modes table
CREATE TABLE IF NOT EXISTS payment_modes (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description         VARCHAR NOT NULL,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    show_at_pos         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Ferry schedules table (branch-wise departure times with assigned ferry)
CREATE TABLE IF NOT EXISTS ferry_schedules (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           INTEGER NOT NULL REFERENCES branches(id),
    departure           TIME NOT NULL,
    capacity            INTEGER NOT NULL DEFAULT 0,
    boat_id             INTEGER REFERENCES boats(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);
CREATE INDEX IF NOT EXISTS ix_ferry_schedules_boat_id ON ferry_schedules(boat_id);
CREATE INDEX IF NOT EXISTS ix_ferry_schedules_branch_departure ON ferry_schedules(branch_id, departure);

-- Item rates table (one rate per item per route)
CREATE TABLE IF NOT EXISTS item_rates (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    levy                NUMERIC(38,2),
    rate                NUMERIC(38,2),
    item_id             INTEGER REFERENCES items(id),
    route_id            INTEGER REFERENCES routes(id),
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID,
    CONSTRAINT check_item_rate CHECK (rate >= 1)
);

-- Portal users table (customer-facing authentication)
CREATE TABLE IF NOT EXISTS portal_users (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(60) NOT NULL,
    last_name           VARCHAR(60) NOT NULL,
    email               VARCHAR(90) NOT NULL,
    password            VARCHAR(255) NOT NULL,
    mobile              VARCHAR(60) NOT NULL,
    google_id           VARCHAR(255) UNIQUE,
    is_verified         BOOLEAN NOT NULL DEFAULT FALSE,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    remember_token      VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    profile_pic         BYTEA[],
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT portal_users_unique_email UNIQUE (email)
);

-- Email OTPs table (verification codes for registration and password reset)
CREATE TABLE IF NOT EXISTS email_otps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(90) NOT NULL,
    otp_hash    VARCHAR(255) NOT NULL,
    purpose     VARCHAR(20) NOT NULL,
    attempts    INTEGER NOT NULL DEFAULT 0,
    is_used     BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_email_otps_email_purpose ON email_otps(email, purpose);

-- Tickets table
CREATE TABLE IF NOT EXISTS tickets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           INTEGER NOT NULL REFERENCES branches(id),
    ticket_no           INTEGER NOT NULL,
    ticket_date         DATE NOT NULL,
    departure           TIME,
    amount              NUMERIC(9,2) NOT NULL,
    discount            NUMERIC(9,2),
    payment_mode_id     INTEGER NOT NULL,
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    net_amount          NUMERIC(9,2) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
    checked_in_at       TIMESTAMPTZ,
    route_id            INTEGER NOT NULL REFERENCES routes(id),
    verification_code   UUID DEFAULT uuid_generate_v4(),
    boat_id             INTEGER REFERENCES boats(id),
    ref_no              VARCHAR(30),
    is_multi_ticket     BOOLEAN NOT NULL DEFAULT FALSE,
    generated_at        TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT ticket_amount_check     CHECK (amount >= 0),
    CONSTRAINT ticket_net_amount_check CHECK (net_amount >= 0)
);

-- Ticket items table
CREATE TABLE IF NOT EXISTS ticket_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id           BIGINT NOT NULL REFERENCES tickets(id),
    item_id             INTEGER NOT NULL REFERENCES items(id),
    rate                NUMERIC(9,2) NOT NULL,
    levy                NUMERIC(9,2) NOT NULL,
    vehicle_no          VARCHAR(15),
    vehicle_name        VARCHAR(60),
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    quantity            INTEGER NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT check_item_quantity CHECK (quantity > 0)
);

-- Ticket payment table
CREATE TABLE IF NOT EXISTS ticket_payement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id           BIGINT NOT NULL,
    payment_mode_id     INTEGER NOT NULL REFERENCES payment_modes(id),
    amount              NUMERIC(9,2) NOT NULL,
    ref_no              VARCHAR(30),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT check_payement_amount CHECK (amount >= 1)
);

-- Refresh tokens (persistent refresh token store)
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID REFERENCES users(id) ON DELETE CASCADE,
    portal_user_id INTEGER REFERENCES portal_users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(255) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  UUID DEFAULT uuid_generate_v4(),
    updated_by  UUID DEFAULT uuid_generate_v4()
);

-- Company table (organization details)
CREATE TABLE IF NOT EXISTS company (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(120) NOT NULL,
    short_name          VARCHAR(60) NOT NULL,
    reg_address         VARCHAR(255) NOT NULL,
    gst_no              VARCHAR(60) NOT NULL,
    pan_no              VARCHAR(60) NOT NULL,
    tan_no              VARCHAR(60) NOT NULL,
    cin_no              VARCHAR(60) NOT NULL,
    contact             VARCHAR(255),
    email               VARCHAR(60) NOT NULL,
    sf_item_id          INTEGER,
    active_theme        VARCHAR(50) DEFAULT 'ocean',
    time_lock_enabled   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4()
);

-- Bookings table (online/portal bookings)
CREATE TABLE IF NOT EXISTS bookings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id           INTEGER NOT NULL REFERENCES branches(id),
    booking_no          INTEGER NOT NULL,
    booking_date        DATE NOT NULL,
    travel_date         DATE,
    departure           TIME,
    amount              NUMERIC(9,2) NOT NULL,
    discount            NUMERIC(9,2),
    payment_mode_id     INTEGER NOT NULL,
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    net_amount          NUMERIC(9,2) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    checked_in_at       TIMESTAMPTZ,
    route_id            INTEGER NOT NULL REFERENCES routes(id),
    portal_user_id      INTEGER NOT NULL REFERENCES portal_users(id),
    verification_code   UUID DEFAULT uuid_generate_v4(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT check_amount     CHECK (amount >= 1),
    CONSTRAINT check_net_amount CHECK (net_amount >= 1)
);

-- Booking items table
CREATE TABLE IF NOT EXISTS booking_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT NOT NULL REFERENCES bookings(id),
    item_id             INTEGER NOT NULL,
    rate                NUMERIC(9,2) NOT NULL,
    levy                NUMERIC(9,2) NOT NULL,
    vehicle_no          VARCHAR(15),
    is_cancelled        BOOLEAN NOT NULL DEFAULT FALSE,
    quantity            INTEGER NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    created_by          UUID DEFAULT uuid_generate_v4(),
    updated_by          UUID DEFAULT uuid_generate_v4(),
    CONSTRAINT quantity_check CHECK (quantity > 0)
);

-- Payment transactions table (gateway payments)
CREATE TABLE IF NOT EXISTS payment_transactions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id          BIGINT NOT NULL REFERENCES bookings(id),
    client_txn_id       VARCHAR(64) NOT NULL UNIQUE,
    gateway_txn_id      VARCHAR(64),
    amount              NUMERIC(9,2) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'INITIATED',
    payment_mode        VARCHAR(30),
    bank_name           VARCHAR(100),
    gateway_message     VARCHAR(255),
    raw_response        TEXT,
    platform            VARCHAR(10) NOT NULL DEFAULT 'web',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_booking_id ON payment_transactions(booking_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_client_txn_id ON payment_transactions(client_txn_id);

-- Rate change logs table (tracks item rate modifications)
CREATE TABLE IF NOT EXISTS rate_change_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                DATE NOT NULL,
    time                TIME NOT NULL,
    route_id            INTEGER NOT NULL REFERENCES routes(id),
    item_id             INTEGER NOT NULL REFERENCES items(id),
    old_rate            NUMERIC(38,2),
    new_rate            NUMERIC(38,2),
    updated_by_user     UUID NOT NULL REFERENCES users(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique indexes on verification_code columns (QR codes must be unique)
CREATE UNIQUE INDEX IF NOT EXISTS idx_tickets_verification_code ON tickets(verification_code) WHERE verification_code IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_bookings_verification_code ON bookings(verification_code) WHERE verification_code IS NOT NULL;

-- System update logs table (audit trail)
CREATE TABLE IF NOT EXISTS sys_update_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name         VARCHAR(30) NOT NULL,
    old_data            JSONB NOT NULL,
    new_data            JSONB NOT NULL,
    updated_by          UUID NOT NULL DEFAULT uuid_generate_v4(),
    updated_at          TIME WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Daily report recipients table
CREATE TABLE IF NOT EXISTS daily_report_recipients (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    label VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User sessions table (tracks login/logout activity)
CREATE TABLE IF NOT EXISTS user_sessions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id          VARCHAR(36) NOT NULL,
    started_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at            TIMESTAMPTZ,
    last_heartbeat      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_reason          VARCHAR(20),
    ip_address          VARCHAR(45),
    city                VARCHAR(100),
    user_agent          VARCHAR(255)
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Users
CREATE INDEX IF NOT EXISTS idx_users_email    ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role     ON users(role);

-- Refresh tokens
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id    ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token_hash ON refresh_tokens(token_hash);

-- Performance indexes for report queries
CREATE INDEX IF NOT EXISTS idx_tickets_date_branch_route
    ON tickets (ticket_date, branch_id, route_id);
CREATE INDEX IF NOT EXISTS idx_tickets_payment_mode
    ON tickets (payment_mode_id);
CREATE INDEX IF NOT EXISTS idx_bookings_date_branch_route
    ON bookings (travel_date, branch_id, route_id);
CREATE INDEX IF NOT EXISTS idx_bookings_portal_user
    ON bookings (portal_user_id);
CREATE INDEX IF NOT EXISTS idx_ticket_payement_ticket_id
    ON ticket_payement (ticket_id);
CREATE INDEX IF NOT EXISTS idx_booking_items_booking_id
    ON booking_items (booking_id);

-- Rate change logs
CREATE INDEX IF NOT EXISTS idx_rate_change_logs_date
    ON rate_change_logs (date);
CREATE INDEX IF NOT EXISTS idx_rate_change_logs_updated_by
    ON rate_change_logs (updated_by_user);

-- User sessions
CREATE INDEX IF NOT EXISTS ix_user_sessions_user_id
    ON user_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_user_sessions_ended_at
    ON user_sessions (ended_at);
CREATE INDEX IF NOT EXISTS ix_user_sessions_started_at
    ON user_sessions (started_at);
CREATE UNIQUE INDEX IF NOT EXISTS ix_user_sessions_session_id
    ON user_sessions (session_id);

-- ============================================================
-- FUNCTIONS & TRIGGERS
-- ============================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_users_updated_at ON users;
CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================
-- PATCH SECTIONS — for migrating existing databases
-- These are safe to re-run (IF NOT EXISTS / IF EXISTS guards).
-- ============================================================

-- PATCH: Add boat_id to tickets
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS boat_id INTEGER REFERENCES boats(id);

-- PATCH: Add ref_no to tickets
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS ref_no VARCHAR(30);

-- PATCH: Add version column for optimistic concurrency control on ticket edits.
-- Frontend sends the version it loaded; backend rejects with 409 if DB version moved.
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;

-- PATCH: Add vehicle_name to ticket_items
ALTER TABLE ticket_items ADD COLUMN IF NOT EXISTS vehicle_name VARCHAR(60);

-- PATCH: Add booking_date to bookings
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS booking_date DATE;

-- PATCH: Replace boats.branch_id with boats.route_id
-- A ferry operates between two ports (a route), not at a single branch.
-- branch_id was added but never wired into the ORM/business logic, so this
-- repurpose is non-destructive (verified on prod: 0 rows had branch_id set).
ALTER TABLE boats DROP CONSTRAINT IF EXISTS boats_branch_id_fkey;
ALTER TABLE boats DROP COLUMN IF EXISTS branch_id;
ALTER TABLE boats ADD COLUMN IF NOT EXISTS route_id INTEGER REFERENCES routes(id);
CREATE INDEX IF NOT EXISTS ix_boats_route_id ON boats(route_id);

-- PATCH: Remove branch_id from item_rates (revert to route-only pricing)
DROP INDEX IF EXISTS uq_item_rate_direction;
ALTER TABLE item_rates DROP COLUMN IF EXISTS branch_id;
CREATE UNIQUE INDEX IF NOT EXISTS uq_item_rate_route
  ON item_rates (item_id, route_id);

-- PATCH: Remove applicable_from_date from item_rates
DROP INDEX IF EXISTS uq_item_rate_route;
DELETE FROM item_rates a
  USING item_rates b
  WHERE a.item_id = b.item_id
    AND a.route_id = b.route_id
    AND a.id < b.id;
ALTER TABLE item_rates DROP COLUMN IF EXISTS applicable_from_date;
CREATE UNIQUE INDEX IF NOT EXISTS uq_item_rate_route
  ON item_rates (item_id, route_id);

-- PATCH: Fix item_rates.updated_by default (random UUIDs look like real user IDs)
ALTER TABLE item_rates ALTER COLUMN updated_by DROP DEFAULT;

-- PATCH: Add CHECK constraints on status fields
ALTER TABLE tickets DROP CONSTRAINT IF EXISTS ticket_status_check;
ALTER TABLE tickets ADD CONSTRAINT ticket_status_check
    CHECK (status IN ('CONFIRMED', 'CANCELLED', 'VERIFIED'));

ALTER TABLE bookings DROP CONSTRAINT IF EXISTS booking_status_check;
ALTER TABLE bookings ADD CONSTRAINT booking_status_check
    CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'VERIFIED'));

ALTER TABLE payment_transactions DROP CONSTRAINT IF EXISTS payment_txn_status_check;
ALTER TABLE payment_transactions ADD CONSTRAINT payment_txn_status_check
    CHECK (status IN ('INITIATED', 'SUCCESS', 'FAILED', 'ABORTED'));

-- PATCH: Add capacity column to ferry_schedules
ALTER TABLE ferry_schedules ADD COLUMN IF NOT EXISTS capacity INTEGER NOT NULL DEFAULT 0;

-- PATCH: Add boat_id to ferry_schedules (schedule-based ferry rotation)
-- Each schedule slot owns the ferry that runs it; ticket creation looks up
-- the matching (branch_id, departure) row to stamp boat_id on new tickets.
ALTER TABLE ferry_schedules ADD COLUMN IF NOT EXISTS boat_id INTEGER REFERENCES boats(id);
CREATE INDEX IF NOT EXISTS ix_ferry_schedules_boat_id ON ferry_schedules(boat_id);
CREATE INDEX IF NOT EXISTS ix_ferry_schedules_branch_departure ON ferry_schedules(branch_id, departure);

-- PATCH: Add account lockout fields to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;

-- PATCH: Add mobile_number to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(20);

-- PATCH: Increase portal_users.password column length
ALTER TABLE portal_users ALTER COLUMN password TYPE VARCHAR(255);

-- PATCH: Add google_id, is_verified, is_active to portal_users
ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS google_id VARCHAR(255) UNIQUE;
ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

-- PATCH: Make users.email nullable
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;

-- PATCH: Add portal_user_id to refresh_tokens and make user_id nullable
ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS portal_user_id INTEGER REFERENCES portal_users(id) ON DELETE CASCADE;
ALTER TABLE refresh_tokens ALTER COLUMN user_id DROP NOT NULL;

-- PATCH: Add active_theme to company
ALTER TABLE company ADD COLUMN IF NOT EXISTS active_theme VARCHAR(50) DEFAULT 'ocean';

-- PATCH: Rename payment_transactions columns (sabpaisa → gateway)
-- Only runs if old column names exist; safe to re-run.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payment_transactions' AND column_name = 'sabpaisa_txn_id') THEN
        ALTER TABLE payment_transactions RENAME COLUMN sabpaisa_txn_id TO gateway_txn_id;
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'payment_transactions' AND column_name = 'sabpaisa_message') THEN
        ALTER TABLE payment_transactions RENAME COLUMN sabpaisa_message TO gateway_message;
    END IF;
END $$;

-- ============================================================
-- AUDIT INFRASTRUCTURE
-- ============================================================

-- Item rate history — append-only audit log for every rate change.
CREATE TABLE IF NOT EXISTS item_rate_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_rate_id    INTEGER NOT NULL,
    item_id         INTEGER NOT NULL,
    route_id        INTEGER NOT NULL,
    old_rate        NUMERIC(38,2),
    new_rate        NUMERIC(38,2),
    old_levy        NUMERIC(38,2),
    new_levy        NUMERIC(38,2),
    old_is_active   BOOLEAN,
    new_is_active   BOOLEAN,
    change_type     VARCHAR(20) NOT NULL
                        CHECK (change_type IN ('CREATED', 'UPDATED', 'DEACTIVATED')),
    changed_by      UUID,
    changed_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT
);

CREATE INDEX IF NOT EXISTS idx_item_rate_history_item_id
    ON item_rate_history (item_id);
CREATE INDEX IF NOT EXISTS idx_item_rate_history_route_id
    ON item_rate_history (route_id);
CREATE INDEX IF NOT EXISTS idx_item_rate_history_changed_at
    ON item_rate_history (changed_at DESC);

-- Item migration map — record of item restructuring events.
CREATE TABLE IF NOT EXISTS item_migration_map (
    id              SERIAL PRIMARY KEY,
    old_item_id     INTEGER,
    old_item_name   VARCHAR(60),
    new_item_id     INTEGER,
    new_item_name   VARCHAR(60),
    migration_label VARCHAR(60) NOT NULL,
    action          VARCHAR(20) NOT NULL
                        CHECK (action IN ('RENAMED', 'RECYCLED', 'DEACTIVATED')),
    migrated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT
);

-- Snapshot columns on ticket_items (set at ticket-creation time, never updated).
ALTER TABLE ticket_items
    ADD COLUMN IF NOT EXISTS item_name_snapshot       VARCHAR(60),
    ADD COLUMN IF NOT EXISTS item_short_name_snapshot VARCHAR(30);

-- Snapshot columns on booking_items.
ALTER TABLE booking_items
    ADD COLUMN IF NOT EXISTS item_name_snapshot       VARCHAR(60),
    ADD COLUMN IF NOT EXISTS item_short_name_snapshot VARCHAR(30);

-- Trigger: audit log for item_rates changes.
CREATE OR REPLACE FUNCTION record_item_rate_change()
RETURNS TRIGGER AS $$
DECLARE
    v_notes TEXT;
    v_change_type VARCHAR(20);
BEGIN
    v_notes := current_setting('app.migration_notes', true);
    IF v_notes = '' THEN v_notes := NULL; END IF;

    IF TG_OP = 'INSERT' THEN
        INSERT INTO item_rate_history
            (item_rate_id, item_id, route_id,
             old_rate, new_rate, old_levy, new_levy,
             old_is_active, new_is_active,
             change_type, changed_by, notes)
        VALUES
            (NEW.id, NEW.item_id, NEW.route_id,
             NULL, NEW.rate, NULL, NEW.levy,
             NULL, NEW.is_active,
             'CREATED', NEW.updated_by, v_notes);

    ELSIF TG_OP = 'UPDATE' THEN
        IF OLD.rate       IS DISTINCT FROM NEW.rate
        OR OLD.levy       IS DISTINCT FROM NEW.levy
        OR OLD.is_active  IS DISTINCT FROM NEW.is_active THEN

            v_change_type := CASE
                WHEN NOT NEW.is_active AND OLD.is_active THEN 'DEACTIVATED'
                ELSE 'UPDATED'
            END;

            INSERT INTO item_rate_history
                (item_rate_id, item_id, route_id,
                 old_rate, new_rate, old_levy, new_levy,
                 old_is_active, new_is_active,
                 change_type, changed_by, notes)
            VALUES
                (NEW.id, NEW.item_id, NEW.route_id,
                 OLD.rate, NEW.rate, OLD.levy, NEW.levy,
                 OLD.is_active, NEW.is_active,
                 v_change_type, NEW.updated_by, v_notes);
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS item_rate_audit ON item_rates;
CREATE TRIGGER item_rate_audit
    AFTER INSERT OR UPDATE ON item_rates
    FOR EACH ROW EXECUTE FUNCTION record_item_rate_change();

-- PATCH: Add time_lock_enabled to company
ALTER TABLE company ADD COLUMN IF NOT EXISTS time_lock_enabled BOOLEAN NOT NULL DEFAULT TRUE;

-- PATCH: SuperAdmin mobile app — push device registry + health event log
CREATE TABLE IF NOT EXISTS push_devices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expo_push_token VARCHAR(255) NOT NULL UNIQUE,
    device_label VARCHAR(120),
    platform VARCHAR(20) NOT NULL DEFAULT 'android',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_push_devices_user_id ON push_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_push_devices_active ON push_devices(is_active) WHERE is_active = TRUE;

CREATE TABLE IF NOT EXISTS system_health_events (
    id BIGSERIAL PRIMARY KEY,
    server_name VARCHAR(40) NOT NULL,
    severity VARCHAR(10) NOT NULL CHECK (severity IN ('INFO', 'WARN', 'CRIT')),
    check_name VARCHAR(80) NOT NULL,
    message TEXT NOT NULL,
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    acked_at TIMESTAMPTZ,
    acked_by UUID REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_system_health_events_created_at ON system_health_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_health_events_server ON system_health_events(server_name);
CREATE INDEX IF NOT EXISTS idx_system_health_events_severity ON system_health_events(severity);
CREATE INDEX IF NOT EXISTS idx_system_health_events_unacked ON system_health_events(created_at DESC) WHERE acked_at IS NULL;
-- PATCH: ack columns for upgrades from earlier rev
ALTER TABLE system_health_events ADD COLUMN IF NOT EXISTS acked_at TIMESTAMPTZ;
ALTER TABLE system_health_events ADD COLUMN IF NOT EXISTS acked_by UUID REFERENCES users(id);

-- ============================================================
-- END OF DDL
-- ============================================================
