-- Migration: Add email OTP verification support
-- Run this against existing databases to add the new table and column

-- 1. Add is_verified column to portal_users
ALTER TABLE portal_users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;

-- Mark all existing users as verified so they're not locked out
UPDATE portal_users SET is_verified = TRUE WHERE is_verified = FALSE;

-- 2. Create email_otps table
CREATE TABLE IF NOT EXISTS email_otps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(90) NOT NULL,
    otp_hash    VARCHAR(255) NOT NULL,
    purpose     VARCHAR(20) NOT NULL,
    attempts    INTEGER NOT NULL DEFAULT 0,
    is_used     BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_otps_email_purpose ON email_otps(email, purpose);
